Corrected release path

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -52,9 +52,8 @@ jobs:
       - name: Upload Artifact
         uses: actions/upload-artifact@v3
         with:
-          name: ul-shopify-debug-apk
+          name: ul-shopify-apk
           path: android/app/build/outputs/apk/debug/ul-shopify.apk
-
 
   build-ios:
     runs-on: macos-latest
@@ -76,28 +75,26 @@ jobs:
           sudo gem install cocoapods
           pod install
 
-      - name: Build iOS .app for Simulator
-        run: |
-          cd ios
-          xcodebuild -workspace ulshopify.xcworkspace \
-                     -scheme ulshopify \
-                     -sdk iphonesimulator \
-                     -configuration Debug \
-                     -derivedDataPath ./build
+      - name: Build iOS .app for Simulator (Release Mode)
+        run: npx react-native run-ios --mode Release
 
-      - name: Rename .app for Simulator
+      - name: Locate and Rename .app for Simulator
         run: |
-          APP_PATH=$(find ios/build -name "*.app" -type d | head -n 1)
-          echo "$APP_PATH"
+          APP_PATH=$(find $HOME/Library/Developer/Xcode/DerivedData -name "ulshopify.app" -type d | head -n 1)
+          echo "App Path: $APP_PATH"
           if [ -n "$APP_PATH" ]; then
-            mkdir -p "ios/build/Products/Debug-iphonesimulator/ul-shopify.app"
-            cp -R "$APP_PATH"/* "ios/build/Products/Debug-iphonesimulator/ul-shopify.app"
+            DEST_PATH="ios/build/Release-iphonesimulator/ul-shopify.app"
+            mkdir -p $DEST_PATH
+            cp -R "$APP_PATH"/* $DEST_PATH
+          else
+            echo "Error: .app file not found"
+            exit 1
           fi
         id: rename-app
 
       - name: Zip the .app directory
         run: |
-          cd ios/build/Products/Debug-iphonesimulator
+          cd ios/build/Release-iphonesimulator
           zip -r ul-shopify.app.zip ul-shopify.app
         id: zip-app
 
@@ -105,7 +102,7 @@ jobs:
         uses: actions/upload-artifact@v3
         with:
           name: ul-shopify-app
-          path: ios/build/Products/Debug-iphonesimulator/ul-shopify.app.zip
+          path: ios/build/Release-iphonesimulator/ul-shopify.app.zip
 
   create-release:
     needs: [build-android, build-ios]
